version: '3.7'

x-base: &base
  volumes:
    - "$HOME/.aws:/root/.aws"
    - "$HOME/.kube:/root/.kube"
    - ".:/go/src/github.com/wrasdf/golang-coding"
  working_dir: /go/src/github.com/wrasdf/golang-coding
  environment:
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-southeast-2}
    - AWS_PROFILE

services:

  sh:
    <<: *base
    build:
      context: .
      target: builder
    entrypoint: bash

  k8s-toolkit:
    <<: *base
    image: ikerry/k8s-toolkit:latest
    user: root
    entrypoint: bash

  release:
    <<: *base
    build:
      context: .
      target: release
    image: ikerry/code:latest:${APP_VERSION:-latest}