version: "3.2"

services:

  golang: &base
    build: .
    working_dir: /go/src/app
    volumes:
      - ".:/go/src/app"

  sh:
    <<: *base
    entrypoint:
      - "/bin/bash"

  test:
    <<: *base
    entrypoint:
      - "go"
      - "test"
      - "./tests"
