required = [
  "github.com/onsi/ginkgo",
  "github.com/onsi/gomega"
]

[prune]
  non-go = true

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "v1.6.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "v1.4.2"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"
